export const data = [
	{
		id                 : 1,
		title              : 'Iron Man',
		releaseOrder       : 1,
		chronologicalOrder : 3,
		starring           : [ 'Robert Downey Jr', 'Terrence Howard', 'Jeff Bridges', 'Gwyneth Paltrow' ],
		director           : 'Jon Favreau',
		phase              : 1,
		releaseDate        : 'May 2, 2008',
		description        :
			'After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.',
	},
	{
		id                 : 2,
		title              : 'The Incredible Hulk',
		releaseOrder       : 2,
		chronologicalOrder : 5,
		starring           : [ 'Edward Norton', 'Liv Tyler', 'Tim Roth', 'William Hurt' ],
		director           : 'Louis Leterrier',
		phase              : 1,
		releaseDate        : 'June 12, 2008',
		description        :
			'Scientist Bruce Banner scours the planet for an antidote to the unbridled force of rage within him: the Hulk. But when the military masterminds who dream of exploiting his powers force him back to civilization, he finds himself coming face to face with a new, deadly foe.',
	},
	{
		id                 : 3,
		title              : 'Iron Man 2',
		releaseOrder       : 3,
		chronologicalOrder : 4,
		starring           : [ 'Robert Downey Jr', 'Gwyneth Paltrow, Don Cheadle, Scarlett Johansson' ],
		director           : 'Jon Favreau',
		phase              : 1,
		releaseDate        : 'May 7, 2010',
		description        :
			"With the world now aware of his dual life as the armored superhero Iron Man, billionaire inventor Tony Stark faces pressure from the government, the press and the public to share his technology with the military. Unwilling to let go of his invention, Stark, with Pepper Potts and James 'Rhodey' Rhodes at his side, must forge new alliances – and confront powerful enemies.",
	},
	{
		id                 : 4,
		title              : 'Thor',
		releaseOrder       : 4,
		chronologicalOrder : 6,
		starring           : [ 'Chris Hemsworth', 'Natalie Portman', 'Tom Hiddleston', 'Anthony Hopkins' ],
		director           : 'Kenneth Branagh',
		phase              : 1,
		releaseDate        : 'May 6, 2011',
		description        :
			"Against his father Odin's will, The Mighty Thor - a powerful but arrogant warrior god - recklessly reignites an ancient war. Thor is cast down to Earth and forced to live among humans as punishment. Once here, Thor learns what it takes to be a true hero when the most dangerous villain of his world sends the darkest forces of Asgard to invade Earth.",
	},
	{
		id                 : 5,
		title              : 'Captain America: The First Avenger',
		releaseOrder       : 5,
		chronologicalOrder : 1,
		starring           : [ 'Chris Evans', 'Hayley Atwell', 'Sebastian Stan', 'Tommy Lee Jones' ],
		director           : 'Joe Johnston',
		phase              : 1,
		releaseDate        : 'July 22, 2011',
		description        :
			"During World War II, Steve Rogers is a sickly man from Brooklyn who's transformed into super-soldier Captain America to aid in the war effort. Rogers must stop the Red Skull – Adolf Hitler's ruthless head of weaponry, and the leader of an organization that intends to use a mysterious device of untold powers for world domination.",
	},
	{
		id                 : 6,
		title              : 'The Avengers',
		releaseOrder       : 6,
		chronologicalOrder : 7,
		starring           : [ 'Robert Downey Jr', 'Chris Evans', 'Chris Hemsworth', 'Mark Ruffalo' ],
		director           : 'Joss Whedon',
		phase              : 1,
		releaseDate        : 'May 4, 2012',
		description        :
			'When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!',
	},
	{
		id                 : 7,
		title              : 'Iron Man 3',
		releaseOrder       : 7,
		chronologicalOrder : 8,
		starring           : [ 'Robert Downey Jr', 'Gwyneth Paltrow', 'Don Cheadle', 'Guy Pearce' ],
		director           : 'Shane Black',
		phase              : 2,
		releaseDate        : 'May 3, 2013',
		description        :
			"When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.",
	},
	{
		id                 : 8,
		title              : 'Thor: The Dark World',
		releaseOrder       : 8,
		chronologicalOrder : 9,
		starring           : [ 'Chris Hemsworth', 'Natalie Portman', 'Tom Hiddleston', 'Anthony Hopkins' ],
		director           : 'Alan Taylor',
		phase              : 2,
		releaseDate        : 'November 8, 2013',
		description        :
			'Thor fights to restore order across the cosmos… but an ancient race led by the vengeful Malekith returns to plunge the universe back into darkness. Faced with an enemy that even Odin and Asgard cannot withstand, Thor must embark on his most perilous and personal journey yet, one that will reunite him with Jane Foster and force him to sacrifice everything to save us all.',
	},
	{
		id                 : 9,
		title              : 'Captain America: The Winter Soldier',
		releaseOrder       : 9,
		chronologicalOrder : 10,
		starring           : [ 'Chris Evans', 'Samuel L. Jackson', 'Scarlet Johansson', 'Robert Redford' ],
		director           : 'Anthony and Joe Russo',
		phase              : 2,
		releaseDate        : 'April 4, 2014',
		description        :
			'After the cataclysmic events in New York with The Avengers, Steve Rogers, aka Captain America is living quietly in Washington, D.C. and trying to adjust to the modern world. But when a S.H.I.E.L.D. colleague comes under attack, Steve becomes embroiled in a web of intrigue that threatens to put the world at risk. Joining forces with the Black Widow, Captain America struggles to expose the ever-widening conspiracy while fighting off professional assassins sent to silence him at every turn. When the full scope of the villainous plot is revealed, Captain America and the Black Widow enlist the help of a new ally, the Falcon. However, they soon find themselves up against an unexpected and formidable enemy—the Winter Soldier.',
	},
	{
		id                 : 10,
		title              : 'Guardians of the Galaxy',
		releaseOrder       : 10,
		chronologicalOrder : 11,
		starring           : [ 'Chris Pratt', 'Zoe Saldana', 'Dave Bautista', 'Vin Diesel' ],
		director           : 'James Gunn',
		phase              : 2,
		releaseDate        : 'August 1, 2014',
		description        :
			'Light years from Earth, 26 years after being abducted, Peter Quill finds himself the prime target of a manhunt after discovering an orb wanted by Ronan the Accuser.',
	},
	{
		id                 : 11,
		title              : 'Avengers: Age of Ultron',
		releaseOrder       : 11,
		chronologicalOrder : 13,
		starring           : [ 'Robert Downey Jr', 'Chris Evans', 'Chris Hemsworth', 'Mark Ruffalo' ],
		director           : 'Joss Whedon',
		phase              : 2,
		releaseDate        : 'May 1, 2015',
		description        :
			'When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to The Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.',
	},
	{
		id                 : 12,
		title              : 'Ant-Man',
		releaseOrder       : 12,
		chronologicalOrder : 14,
		starring           : [ 'Paul Rudd', 'Michael Douglas', 'Evangeline Lilly', 'Corey Stoll' ],
		director           : 'Peyton Reed',
		phase              : 2,
		releaseDate        : 'June 29, 2015',
		description        :
			'Armed with the astonishing ability to shrink in scale but increase in strength, master thief Scott Lang must embrace his inner-hero and help his mentor, Doctor Hank Pym, protect the secret behind his spectacular Ant-Man suit from a new generation of towering threats. Against seemingly insurmountable obstacles, Pym and Lang must plan and pull off a heist that will save the world.',
	},
	{
		id                 : 13,
		title              : 'Captain America: Civil War',
		releaseOrder       : 13,
		chronologicalOrder : 15,
		starring           : [ 'Chris Evans', 'Robert Downey Jr', 'Scarlett Johansson', 'Sebastian Stan' ],
		director           : 'Anthony and Joe Russo',
		phase              : 3,
		releaseDate        : 'April 12, 2016',
		description        :
			'Following the events of Age of Ultron, the collective governments of the world pass an act designed to regulate all superhuman activity. This polarizes opinion amongst the Avengers, causing two factions to side with Iron Man or Captain America, which causes an epic battle between former allies.',
	},
	{
		id                 : 14,
		title              : 'Doctor Strange',
		releaseOrder       : 14,
		chronologicalOrder : 17,
		starring           : [ 'Benedict Cumberbatch', 'Chiwetel Ejiofor', 'Rachel McAdams', 'Benedict Wong' ],
		director           : 'Scott Derrickson',
		phase              : 3,
		releaseDate        : 'November 4, 2016',
		description        :
			'After his career is destroyed, a brilliant but arrogant surgeon gets a new lease on life when a sorcerer takes him under her wing and trains him to defend the world against evil.',
	},
	{
		id                 : 15,
		title              : 'Guardians of the Galaxy Vol. 2',
		releaseOrder       : 15,
		chronologicalOrder : 12,
		starring           : [ 'Chris Pratt', 'Zoe Saldana', 'Dave Bautista', 'Vin Diesal' ],
		director           : 'James Gunn',
		phase              : 3,
		releaseDate        : 'May 5, 2017',
		description        :
			"The Guardians must fight to keep their newfound family together as they unravel the mysteries of Peter Quill's true parentage.",
	},
	{
		id                 : 16,
		title              : 'Spider-Man: Homecoming',
		releaseOrder       : 16,
		chronologicalOrder : 16,
		starring           : [ 'Tom Holland', 'Michael Keaton', 'Robert Downey Jr', 'Marisa Tomei' ],
		director           : 'Jon Watts',
		phase              : 3,
		releaseDate        : 'July 7, 2017',
		description        :
			'Following the events of Captain America: Civil War, Peter Parker, with the help of his mentor Tony Stark, tries to balance his life as an ordinary high school student in Queens, New York City, with fighting crime as his superhero alter ego Spider-Man as a new threat, the Vulture, emerges.',
	},
	{
		id                 : 17,
		title              : 'Thor: Ragnarok',
		releaseOrder       : 17,
		chronologicalOrder : 19,
		starring           : [ 'Chris Hemsworth', 'Mark Ruffalo', 'Tom Hiddleston', 'Cate Blanchett' ],
		director           : 'Taika Waititi',
		phase              : 3,
		releaseDate        : 'October 10, 2017',
		description        :
			'Thor is imprisoned on the other side of the universe and finds himself in a race against time to get back to Asgard to stop Ragnarok, the destruction of his home-world and the end of Asgardian civilization, at the hands of an all-powerful new threat, the ruthless Hela.',
	},
	{
		id                 : 18,
		title              : 'Black Panther',
		releaseOrder       : 18,
		chronologicalOrder : 18,
		starring           : [ 'Chadwick Boseman', 'Michael B. Jordan', "Lupita Nyong'o", 'Danai Gurira' ],
		director           : 'Ryan Coogler',
		phase              : 3,
		releaseDate        : 'January 29, 2018',
		description        :
			"King T'Challa returns home from America to the reclusive, technologically advanced African nation of Wakanda to serve as his country's new leader. However, T'Challa soon finds that he is challenged for the throne by factions within his own country as well as without. Using powers reserved to Wakandan kings, T'Challa assumes the Black Panther mantel to join with girlfriend Nakia, the queen-mother, his princess-kid sister, members of the Dora Milaje (the Wakandan 'special forces') and an American secret agent, to prevent Wakanda from being dragged into a world war.",
	},
	{
		id                 : 19,
		title              : 'Avengers: Infinity War',
		releaseOrder       : 19,
		chronologicalOrder : 20,
		starring           : [ 'Robert Downey Jr', 'Chris Hemsworth', 'Chris Evans', 'Mark Ruffalo' ],
		director           : 'Anthony and Joe Russo',
		phase              : 3,
		releaseDate        : 'April 23, 2018',
		description        :
			'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.',
	},
	{
		id                 : 20,
		title              : 'Ant-Man and the Wasp',
		releaseOrder       : 20,
		chronologicalOrder : 21,
		starring           : [ 'Paul Rudd', 'Evangeline Lilly', 'Michael Pena', 'Walton Goggins' ],
		director           : 'Peyton Reed',
		phase              : 3,
		releaseDate        : 'June 25, 2018',
		description        :
			'Just when his time under house arrest is about to end, Scott Lang once again puts his freedom at risk to help Hope van Dyne and Dr. Hank Pym dive into the quantum realm and try to accomplish, against time and any chance of success, a very dangerous rescue mission.',
	},
	{
		id                 : 21,
		title              : 'Captain Marvel',
		releaseOrder       : 21,
		chronologicalOrder : 2,
		starring           : [ 'Brie Larson', 'Samuel L. Jackson', 'Ben Mendelsohn', 'Jude Law' ],
		director           : 'Anna Boden and Ryan Fleck',
		phase              : 3,
		releaseDate        : 'March 8, 2019',
		description        :
			'The story follows Carol Danvers as she becomes one of the universe’s most powerful heroes when Earth is caught in the middle of a galactic war between two alien races. Set in the 1990s, Captain Marvel is an all-new adventure from a previously unseen period in the history of the Marvel Cinematic Universe.',
	},
	{
		id                 : 22,
		title              : 'Avengers: Endgame',
		releaseOrder       : 22,
		chronologicalOrder : 22,
		starring           : [ 'Robert Downey', 'Chris Evans', 'Chris Hemsworth', 'Mark Ruffalo' ],
		director           : 'Anthony and Joe Russo',
		phase              : 3,
		releaseDate        : 'April 22, 2019',
		description        :
			"After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
	},
	{
		id                 : 23,
		title              : 'Spider-Man: Far From Home',
		releaseOrder       : 23,
		chronologicalOrder : 23,
		starring           : [ 'Tom Holland', 'Jake Gyllenhaal', 'Zendaya', 'John Favreau' ],
		director           : 'Jon Watts',
		phase              : 3,
		releaseDate        : 'June 26, 2019',
		description        :
			'Peter Parker and his friends go on a summer trip to Europe. However, they will hardly be able to rest - Peter will have to agree to help Nick Fury uncover the mystery of creatures that cause natural disasters and destruction throughout the continent.',
	},
	{
		id                 : 24,
		title              : 'Black Widow',
		releaseOrder       : 24,
		chronologicalOrder : 'N/A',
		starring           : [ 'Scarlett Johansson', 'David Harbour', 'Florence Pugh', 'O.T. Fagbenle' ],
		director           : 'Cate Shortland',
		phase              : 4,
		releaseDate        : 'May 1, 2020',
		description        :
			'At birth the Black Widow (aka Natasha Romanova) is given to the KGB, which grooms her to become its ultimate operative. When the U.S.S.R. breaks up, the government tries to kill her as the action moves to present-day New York, where she is a freelance operative.',
	},
	{
		id                 : 25,
		title              : 'The Eternals',
		releaseOrder       : 25,
		chronologicalOrder : 'N/A',
		starring           : [ 'Angelina Jolie', 'Richard Madden', 'Kumail Nanjiani', 'Salma Hayek' ],
		director           : 'Chloe Zhao',
		phase              : 4,
		releaseDate        : 'November 6, 2020',
		description        :
			'The saga of the Eternals, a race of immortal beings who lived on Earth and shaped its history and civilizations.',
	},
	{
		id                 : 26,
		title              : 'Shang-Chi and the Legend of the Ten Rings',
		releaseOrder       : 26,
		chronologicalOrder : 'N/A',
		starring           : [ 'Awkwafina', 'Simu Liu', 'Tony Chiu-Wai Leung' ],
		director           : 'Destin Daniel Cretton',
		phase              : 4,
		releaseDate        : 'February 12, 2021',
		description        : "The movie, based on Marvel Comics, will focus on Shang-Chi; 'The Master of Kung-Fu'.",
	},
	{
		id                 : 27,
		title              : 'Doctor Strange in the Multiverse of Madness',
		releaseOrder       : 27,
		chronologicalOrder : 'N/A',
		starring           : [ 'Benedict Cumberbatch', 'Elizabeth Olsen' ],
		director           : 'Scott Derrickson',
		phase              : 4,
		releaseDate        : 'May 7, 2021',
		description        : "Plot unknown. Sequel to the 2016 Marvel film 'Doctor Strange.",
	},
	{
		id                 : 28,
		title              : 'Thor: Love and Thunder',
		releaseOrder       : 28,
		chronologicalOrder : 'N/A',
		starring           : [ 'Chris Hemsworth', 'Tessa Thompson', 'Natalie Portman' ],
		director           : 'Taika Waititi',
		phase              : 4,
		releaseDate        : 'November 5, 2021',
		description        : 'Plot is unknown at this time.',
	},
];
